/*============================================================================*/
/**  @file       lingual.h
 **  @ingroup    user_interface
 **  @brief		 All translations and languages
 **
 **  Longer description.
 **
 **  @author     mensfort
 **
 **  @par Classes:
 **              -
 */
/*------------------------------------------------------------------------------
 **  Copyright (c) Bart Houkes, 17 jan 2011
 **
 **  Copyright notice:
 **  This software is property of Bart Houkes.
 **  Unauthorized duplication and disclosure to third parties is forbidden.
 **===========================================================================*/

#pragma once

/*------------- Standard includes --------------------------------------------*/
//#include "name_type.h"
#include <string>
#include "taal_type.h"

#define MAX_LANGUAGE  LANG_NEXT

typedef enum
{
  _JANUAR, _FEBRUAR, _MARCH, _APRIL, _MAY, _JUNE, _JULY, _AUGUST,
  _SEPTEMBER, _OKTOBER, _NOVEMBER, _DECEMBER,
  _JANUAR_SHORT, _FEBRUAR_SHORT, _MARCH_SHORT, _APRIL_SHORT, _MAY_SHORT,
  _JUNE_SHORT, _JULY_SHORT, _AUGUST_SHORT,
  _SEPTEMBER_SHORT, _OKTOBER_SHORT, _NOVEMBER_SHORT, _DECEMBER_SHORT,
  _MONDAY, _TUESDAY, _WEDNESDAY, _THURSDAY, _FRIDAY, _SATURDAY, _SUNDAY,
  _MONDAY_SHORT, _TUESDAY_SHORT, _WEDNESDAY_SHORT, _THURSDAY_SHORT,
  _FRIDAY_SHORT, _SATURDAY_SHORT, _SUNDAY_SHORT,
  _ABORT, _MORE,
  _TAKEAWAY, _KITCHEN1, _KITCHEN2,
  _TABLE1, _TTOTAL, _NUMBER1, _OTHERS,
  _EMPLOYEE, _MANAGER,

  //_AANTAL_P, _ACC,
  _ACCOUNT_ARCHIVE,
  _ACCOUNTREP31, _ACCOUNT_LONG, _ACCOUNT_TODAY,

  _ACCT_GROUP,
  _ACCT_TA_SUBTOTAL, _ACCT_TA_TOTAL,
  _ACCT_SI_SUBTOTAL, _ACCT_SI_TOTAL,

  _ACCT_TA_TAX, _ACCT_SI_TAX,
  _ACCT_SUBTOTAL, _ACCT_TAX, _ACCT_TOTAL,

  _ACCOUNT_ITEM_KITCHEN,
  _ACCOUNT_ITEM_DRINKS,
  _ACCOUNT_ITEM_BAR,
  _ACCOUNT_ITEM_OTHERS,
  _ACCOUNT_ITEM_KITCHEN2,
  _ACCOUNT_ITEM_SUSHI,
  _ACCOUNT_ITEM_NONFOOD,
  _ACCOUNT_ITEM_KITCHEN3,
  _ACCOUNT_ITEM_KITCHEN4,
  _ACCOUNT_ITEM_KITCHEN5,

  _ACCOUNT_CLUSTERS, _ACCOUNT_CLUSTERS_CHANGE, _ACTIVE, _ADD_FOOD, _ADD_FREE_TIME, _ADD_PART, _ADD_STORE,
  _ADD_TABLE, _ADD_TAX_CLUSTER, _AFTER_BILL_ADD_FOOD, _ADD_MENU_CARD,
  _ADD_MONEY, _ADD_TIME30, _ALIGN, _ALL_KEYS, _ALREADY_PAYED,
  _AMERICAN_EXPRESS, _ARTICLES, _ASAP, _BACK,  _BACKGROUND1, _BACKGROUND2, _BACKGROUND_SELECTED,
  _BANK_ACCOUNT, _BAR, _BAR_PRINTER,
  _BEZORGING, _BEZORGKOSTEN,
  _BILL_DEFAULT_DISCOUNT,
  _BILL_HEADER,
  _BILL_PAYMENTS,
  _BILL_TOP_RIGHT, _BILLS_PAYED_OR_NOT,
  //_BILL_NUMBER,
  _BTW_LIST, _BTW_LOW, _BTW_HIGH, _BTW_ZERO, _BTW_NUMBER, _BUY_ON_ACCOUNT, _BUYPRICE,
  //_BTW_PRINT_LIST, __BTW_REMOVE_LIST,
  _CALCULATOR, _CALENDAR, _CANCEL, _CANCEL_REASON,
  _CANCEL_REASON_ADD_FOOD,
  _CANCEL_REASON_BAD_FOOD, _CANCEL_REASON_DELIVERY_PROBLEM, _CANCEL_REASON_MOVE_TABLE,
  _CANCEL_REASON_NO_MONEY, _CANCEL_REASON_NO_STOCK,
  _CANCEL_REASON_PERSONNEL, _CANCEL_REASON_RUN_AWAY, _CANCEL_REASON_TECHNICAL,
  _CANCEL_REASON_TELEPHONE, _CANCEL_REASON_TRAINING, _CANCEL_REASON_WRONG_DISH,
  _CANCEL_REASON_CUSTOMER, _CANCEL_REASON_TOO_LATE, _CLEAN_TABLE, _CONGDATE,
  _SMARTCARD, _CANNOT_DELIVER, _CASH, _CASH_IN, _CASH_OUT,
  _CAT5, _CHANGELANG, _CHANGE_ADDRESS, _CHANGE_ARTICLES,
  _CHANGE_MENU_BARCODES, _CHANGE_BILL, _CHANGE_OTHERS, _CHANGE_FONT,
  _CHANGE_MENU_ALIAS, _CHANGE_MENU_ADD_ARTICLES, _CHANGE_PRINTER,
  _CHANGE_MENU_COLOURS, _CHANGE_MENU_CLUSTERS, _CHANGE_MENUGROUPS, _CHANGE_MENU_MOVE_ARTICLES, _CHANGE_MENU_NAMES,
  _CHANGE_MENU_PICTURES, _CHANGE_MENU_PRICE, _CHANGE_MENU_TAX, _CHANGE_MENU_TYPES,
  _CHECK_OTHER_PRINTER,
  _CHECK_PRINTER, _CHANGE_PROGRAM_COLOURS, _CHARITY, _CHOOSE_LIST, _CHOOSE_MANY, _CHOOSE_FOOD, _CHOOSE_TWIN,
  _CITY, _CLEAR, _CLEAR_PICTURE, _CLEAR_WALLET, _CLIENT,
  _CLIENT_AMOUNT, _CLIENT_CHOOSE,
  _CLIENT_LIST, _CLIENT_PAYS_WITH,
  _CLUSTER_ADD, _CLUSTER_ASK_DUPLICATE, _CLUSTER_ASK_REMOVE, _CLUSTER_DUPLICATE, _CLUSTER_NAME, _CLUSTER_REMOVE,
  _COMPANY, _CONFIGURATION, _CONFIRM,
  _CONFIRM_NOTA, _COOKING_OVERVIEW, _COPY_GROUP,
  _CREDIT, _CREDIT_CARD,
  _CURRENT_STORE, _CUSTOMER, _CUT_PAPER, _DAODATE, _DATE_DELIVERED, _DATE_ORDERED, _DAY, _DAY31,
  _DEBIT, _DELETE, _DELETE_FOOD, _DELETED_FOOD, _DELETED37, _DELIVERED, _DEPOSIT,
  _DESIGN_ADVERTISEMENT,
  _DISCOUNT, _DISCOUNT21, _DOWNLOAD_CONFIGURATION, _DOWNLOAD_MENU,
  _DRINKS_PRINTER, _DRINKS, _DUPLICATE_CUSTOMER, _DUPLICATE_MENU, _EDITNAME, _EDIT_BILL_FOOTER,
  _EDIT_INVENTORY, _EDIT_PART, _EMPTY_TABLE, _END_TIME, _ENTER,
  _CHOOSE_TO_ORDER, _CONFIRM_ITEM, _DATE, _DUPLICATE_ADD,
  _EAT_INSIDE,
  _EMAIL, _ERASE_ALL_KEYS,
  _ERASE_FLOORPLAN, _ERASE_PICTURE, _EXACTLY, _EXCHANGE_MONEY,
  _EXPORT_ACCOUNTING, _EXPORT_CONFIGURATION, _EXPORT_MENU,
  _EXIT, _EXTRA, _FACTORY_MODE, _FIND_FOOD, _FIND_HANDHELD,
  _FINISH_BILL, _FINISH_ORDER, _FLOOR, _FLOOR_CHOOSE, _FONT, _FOOD, _FOOD_READY,
  _GAIBIAN, _GRAPH_DAYS_REPORT, _GRAPH_DISCOUNT, _GRAPH_GROUPS, _GRAPH_GROUPS_REPORT,
  _GRAPH_HOURS_REPORT, _GRAPH_ITEMS, _GRAPH_ITEMS_REPORT,
  _GRAPH_MONTHS_REPORT,
  _GRAPH_QUANTITIES,
  _GRAPH_QUARTER_REPORT, _GRAPH_RFID_KEYS, _GRAPH_TYPE, _GRAPH_TOTALS, _GRAPH_WEEKS_REPORT,
  _GRAPH_YEAR_REPORT,
  _GROUP, _GROUP5, _GROUP16, _HANDWRITING, _HEIGHT, _HELP_COLOUR_DIALOG,
  _HORIZONTAL_SCROLL, _HOUR, _HOWMANYITEMS,
  _ICON, _IDEAL, _IMPORT_CONFIGURATION, _IMPORT_MENU, _IMPORT_SOFTWARE, _IN_ORDER,
  _INCLUDED8, _INFO_ADDRESS_PC, _INFO_MENU_CARD, _INSERT_CUSTOMER, _INSERT_FOOD, _INTERNET, _INVOICE,
  _ITEM_ALL_KITCHEN, _ITEM_BAR, _ITEM_DRINKS, _ITEM_KITCHEN, _ITEM_KITCHEN2,
  _ITEM_KITCHEN3, _ITEM_KITCHEN4, _ITEM_KITCHEN5, _ITEM_NONFOOD,
  _ITEM_OTHERS, _ITEM_SUSHI,
  _KEY_INFO, _KITCHEN,
  _KITCHEN01, _KITCHEN02, _KITCHEN03, _KITCHEN04, _KITCHEN05, _KITCHEN_COLLECT,
  _KITCHEN_INDEX,
  _KOMMA, _LENGTH_TABLE, _LIMIT, _LIST, _LIST42, _LOCK, _LOGIN, _LOGOFF, _MARK_BILLS_SENT, _MASTERCARD,
  _MEENEMEN, _MENULIST, _MENU_PRICE, _MERGE_TABLES, _MINUTES, _MIN10,
  _MOBILE, _MONTH, _MONTH12, _MONTH22, _MOVE_OTHER_TABLE, _MOVE_OTHER_TABLE1,
  _MOVE_GROUP, _MOVE_ITEM,
  _MOVE_TO, _NAME, _NAME34, _NAMEQUANT34,
  _NEW_ADD, _NEW_CUSTOMER, _NEW_ITEM, _NEXT, _NEXT_ADD, _NEW_KEY, _NEXT_ARTICLE,
  _NEXT_SLIP_PAGE, _NON_CASH, _NONFOOD, _NOP, _NOT_PAYED_YET, _NUMBER_ORDER, _NUMBER_PERSONS,
  _NUMBER_TABLES,
  _OFFER, _OK, _OLD_TRANSACTION_JUST_BILL, _ON_THE_ROAD, _OPTIONS, _ORDER,
  _ORDER_ASSEMBLE, _ORDER_CANCEL, _ORDER_DATE, _ORDER_DEPOSIT, _ORDER_FIRST, _ORDER_GETTAKEAWAY,
  _ORDER_TAKEAWAY, _ORDER_TELEPHONE, _ORDER_WAIT,
  __OTHER_BILL, _OTHER, __OUT6, __OUT8, _OVERWRITE, _PAID, __PRINTPAGE, _PAPER_SP200, _PAPER_TM290,
  _PART_NAME, _PARTIAL_BILL, _PASSWORD, _PAY, _PAY_DEBIT, _PAY_ZETTLE, _PAYED,
  _PAYED_TRANSACTIONS, _PAYMENT, _PAYPAL, _PAYS_WITH, _PER_DAY, _PER_MONTH,
  _PER_YEAR, _PERCENTAGE, _PERSON, _PICTURE, _PIN, _PINYIN, _PLACE_ORDER,
  _PORTION, _PREVIOUS_ADD, _PRICE_CHANGE, _PRINT_AGAIN, _PRINT_COLLECT, _PRINT_FOOD,
  _PRINT_KITCHEN, _PRINT_KITCHEN_LOCAL, _PRINT_OFFER, _PRINT_KITCHEN2,
  _PRINT_LIST, _PRINT_PRINTERS, _PRINT_SLIP, _PRINT_ROLL, _PRIJS_PP, _PRINTER, //_PRINTER_READY,
  _PRINTER_DETAILS, _PRINTER_NETWORK_PROBLEM, _PRINT_QUANTITY,
  _PROFIT, _QUANTITY, _QUARTER, _QUICK_CHOOSE, _RADICAL, _RECHAUD, _REMARK,
  _REMOVE_ADD, _REMOVE_CUSTOMER, _REMOVE_CUSTOMER_ASK, _REMOVE_MENU_CARD, _REMOVE_MONEY,
  _REMOVE_FOOD, _REMOVE_PART, _REMOVE_TAX_CLUSTER, _REPRINT,
  _REROUTING,
   _RESERVATION_GRAPH_USED_TABLE, _RESERVATION_GRAPH_FREE_TABLE,
   _RESERVATION_GRAPH_USED_PERSON, _RESERVATION_GRAPH_FREE_PERSON,
   _RESERVATION_GRAPH_USED_TABLES_PERSON, _RESERVATION_GRAPH_FREE_TABLES_PERSON,
  _RESERVE_TABLE, _RESERVED, _RESET_PASSWORD, _RESTAMOUNT, _RESTAURANT,
  _RESTAURANT_PRICE, _RESTAURANT_HALF_PRICE, _RETAILING33,
  _RETAILING_DELETED33, _RETAIL37, _RETOUR_ITEMS, _RFID_KEY_TRANSPORT,
  _ROW_TOP, _ROW_CENTER, _ROW_BOTTOM1, _ROW_BOTTOM2, _ROW_BUTTOM3,
  _SALES_GRAPH,
  _SALES_GRAPH_INFO, _SALES_GRAPH_TYPE,
  _SAVE, _SEARCH, _SEARCH_CUSTOMER, _SELECT_ALL, _SEND_BILL, _SEND_NEW_TIME, _SEQ_TABLE_KITCHEN_TOTAL,
  _SEQA, _SEQ1, _SEQ1A, _SEQ2, _SEQ47, _SERVICE_KEY, _SHIFT, _SHOP, _SHOW_NUMBERS, _SHOW_PERSONS,
  _SHUTDOWN, _SIMPLIFIED,
  _SPLIT_TABLE, _START_COOKING, _STATE, _STATIEGELD,
  _STORE_EMPTY_DATE,
  _STORE_STATUS_CANCELLED,
  _STORE_STATUS_CONSUMED,
  _STORE_STATUS_DELIVERED,
  _STORE_STATUS_DELIVERED_EARLY,
  _STORE_STATUS_DELIVERED_TOO_LATE,
  _STORE_STATUS_EVER_DELIVERED,
  _STORE_STATUS_NOT_ORDERED_YET,
  _STORE_STATUS_ORDERED,
  _STORE_STATUS_PREPARED,
  _STORE_TOTAL_ITEMS,
  _STORE_STATUS_YEAR_CONSUMPTION,
  _STYLE,
  _SUBTOTAL, _SUPPLIER, _SUPPLIER_ADD, _SUPPLIER_REMOVE,
  _SUSHI, _SWITCH_OFF, _UNDO_CHANGES,
  _USB, _TABLE, _TABLET_UPDATE, _TAKEAWAY_PHONE, _TAKEAWAY_PRICE, _TAKEAWAY_HALF_PRICE,
  _TAX4, _TAX_GROUP,
  _TEL, _TELEPHONE, _TEMPORARY_PRICE, _TEXT_COLOUR, _THUIS,
  _THUISBEZORGD, _TICKET, _TIME2, _TIPS, _TODAY,
  _TOTAL, _TOTAL_DRAWER_CHANGES,  _TOTAL_WITHOUT_DISCOUNT, _TOTALOFDAY, _TRADITIONAL, _TRANSACTION, _TRANSACTIONS,
  _TRANSPORT, _TWIN_ITEM, _TYPE_ITEM_ACCESSOIRE, _TYPE_MENU_ADD, _TYPE_COMBINATION_MENU,
  _TYPE_MENU_DESCRIPTION, _TYPE_MENU_EXTRA,_TYPE_MENU_ITEM,
  _TYPE_SALES_ITEM, _TYPE_OUTOFSTOCK, _TYPE_SEPARATOR,
  _UPDATE_ITEM_EXISTING, _UPDATE_OR_NEW, _UPDATE_SOFTWARE, _UPDATE_TO_NEW_ITEM,
  _UPLOAD_ARCHIVE, _UPLOAD_CONFIGURATION, _UPLOAD_LOG,
  _UPLOAD_MENU, _USE_FOR, _USE_FOR_RESTAURANT, _USE_FOR_TAKEAWAY, _USE_FOR_TELEPHONE,
  _VERTALEN, _VIKI, _VISA, _WAIT, _WAIT_DATABASE, _WALL, _WALL_CHOOSE, _WALL_COLOUR,
  _WANTED_TIME, _WARNING_NO_CHANGES, _WEEK_DAYS, _WIDTH, _WOK,
  _YEAR,
  _CHEF_FUNCTION,
  _KEY_FUNCTION, _KEY_BAD, _PAGE_ORDER, _BILL,
  _BILL_OPTION, _TELEPHONE_LOG, _TELEPHONE_ORDER,

  _KEY, _KEY_ERASING, _KEY_ERASING_FIRST,
  _REPORT, _TABLE_MAP_ORDER, _TABLE_MAP_DESIGN, _TABLE_MAP_TABLES, _TIME_CORRECTION,
  _TIME_ERROR, _KEY_SUMMATION, _KEY_CONTROL,

  _REMOVE_KEY, _POSTCODE, _DELIVER_TIME,
  _HOUSENR, _STREET, _VERTICAL_SCROLL, _VISIBLE_ITEM, _WALLET, _WARN_KEY, _WIDTH_TABLE,
     // Leave this as last value.
  _NO_TEXT,
  MAX_LINTEXT
} EtextId;


#define MAX_TIMEPERIOD     4

extern const std::string Lin[MAX_LINTEXT][MAX_LANGUAGE];
extern EtextId findTextId( const std::string &textId);
extern std::string getTranslation( int id, Taal language=LANG_CURRENT);
extern std::string getDate(int month, int day, int year);
